let commands = Object.assign({}, require("./commands/compiler.js"))
commands = Object.assign(commands, require("./commands/config.js"))
commands = Object.assign(commands, require("./commands/connect.js"))
commands = Object.assign(commands, require("./commands/explain.js"))
commands = Object.assign(commands, require("./commands/focus.js"))
commands = Object.assign(commands, require("./commands/hilite.js"))
commands = Object.assign(commands, require("./commands/launch.js"))
commands = Object.assign(commands, require("./commands/macros.js"))
commands = Object.assign(commands, require("./commands/quit.js"))
commands = Object.assign(commands, require("./commands/rename.js"))
commands = Object.assign(commands, require("./commands/set.js"))
commands = Object.assign(commands, require("./commands/stream.js"))
commands = Object.assign(commands, require("./commands/sudo.js"))
commands = Object.assign(commands, require("./commands/swap.js"))
commands = Object.assign(commands, require("./commands/theme.js"))
commands = Object.assign(commands, require("./commands/ui.js"))

exports.commands = commands
